#baseurl = "https://pages.gitlab.io/hugo/"
baseurl = "https://www.cns.s.u-tokyo.ac.jp/test/" # FOR TESTING
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
canonifyurls  = true

DefaultContentLanguage = "ja"
#theme = "beautifulhugo"
theme = "cns_hp_theme"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Languages]
[Languages.ja]
weight = 1
title = "æ±äº¬å¤§å­¦åŸå­æ ¸ç§‘å­¦ç ”ç©¶ã‚»ãƒ³ã‚¿ãƒ¼"
[Languages.en]
weight = 2
title = "Center for Nuclear Study"



[Params]
  subtitle = "Hugo Blog Template for GitLab Pages"
  logo = "img/cns_mark_color.jpg"
  favicon = "img/favicon.ico"
  dateFormat = "2006/01/02"
  commit = false
  rss = true
  comments = false
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"


[[menu.main]]
    identifier = "about"
    name = "CNS¤Ë¤Ä¤¤¤Æ"
    url = "/about"
    weight = 1

[[menu.main]]
    parent = "about"
    name = "¥»¥ó¥¿¡¼Ä¹°§»¢"
    url = "/about/greeting"
    weight = 1

[[menu.main]]
    parent = "about"
    name = "±è³×¡¦ÁÈ¿¥¿Ş"
    url = "/about/history"
    weight = 2
    
[[menu.main]]
    parent = "about"
    name = "¥Ñ¥ó¥Õ¥ì¥Ã¥È"
    url = "/about/pamphlet"
    weight = 3
    
[[menu.main]]
    name = "¹­Êó¡¦¼ÂÀÓ¡¦É¾²Á"
    url = "/about/announcement"
    parent = "about"
    weight = 4
    
[[menu.main]]
    identifier = "for_students"
    name = "¿Ê³Ø´õË¾¤ÎÊı¤Ø"
    url = "/for_students"
    weight = 2
    
[[menu.main]]
    parent = "for_students"
    name = "Âç³Ø±¡¿Ê³Ø¥¬¥¤¥À¥ó¥¹"
    url = "/for_students/guidance"
    weight = 1

[[menu.main]]
    parent = "for_students"
    name = "»ÜÀß¸«³Ø²ñ"
    url = "/for_students/facility_tour"
    weight = 2

[[menu.main]]
    identifier = "lab"
    name = "¿Ê³Ø´õË¾¤ÎÊı¤Ø"
    url = "/research"
    weight = 3

[[menu.main]]
    parent = "lab"
    name = "±§Ãè³ËÊªÍı"
    url = "/research/cosmos"
    weight = 1

[[menu.main]]
    parent = "lab"
    name = "³Ë¥À¥¤¥Ê¥ß¥¯¥¹"
    url = "/research/donuts"
    weight = 2

[[menu.main]]
    parent = "lab"
    name = "¥¯¥©¡¼¥¯ÊªÍı"
    url = "/research/quark"
    weight = 3

[[menu.main]]
    parent = "lab"
    name = "¥¨¥­¥¾¥Á¥Ã¥¯³ËÈ¿±ş"
    url = "/research/enr"
    weight = 4

[[menu.main]]
    parent = "lab"
    name = "¶Ë¸Â¸¶»Ò³Ë¹½Â¤"
    url = "/research/nuspeq"
    weight = 5

[[menu.main]]
    parent = "lab"
    name = "´ğËÜÂĞ¾ÎÀ­"
    url = "/research/edm"
    weight = 6

[[menu.main]]
    parent = "lab"
    name = "²ÃÂ®´ï³«È¯"
    url = "/research/accelerator"
    weight = 7

[[menu.main]]
    parent = "lab"
    name = "OEDO-SHARAQ¥×¥í¥¸¥§¥¯¥È"
    url = "/research/sharaq"
    weight = 8

[[menu.main]]
    parent = "lab"
    name = "¸¶»Ò³ËÍıÏÀ"
    url = "/research/theory"
    weight = 9

[[menu.main]]
    name = "¶µ°÷¾Ò²ğ"
    url = "/staffs"
    weight = 4

[[menu.main]]
    name = "¥¤¥Ù¥ó¥È¾ğÊó"
    url = "/events"
    weight = 5

[[menu.main]]
    name = "¹ñºİ¥µ¥Ş¡¼¥¹¥¯¡¼¥ë"
    url = "/cnsss"
    weight = 6

[[menu.main]]
    name = "¥»¥ß¥Ê¡¼³«ºÅ°ÆÆâ"
    url = "/seminers"
    weight = 7

[[menu.main]]
    name = "¥¢¥¯¥»¥¹"
    url = "/access"
    weight = 8

